name: Workflows Environment Setup

description: "PHP environment setup"

runs:
  using: composite

  steps:
    - name: Composer cache
      id: composer_cache
      uses: actions/cache@v3
      with:
        path: ./vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "8.1"

    - name: Install composer
      shell: bash
      if: steps.composer_cache.outputs.cache-hit != 'true'
      run: |
        echo 'Install packages'
        composer install -n --prefer-dist
