name: PHPUnit

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run phpunit
        run: vendor/bin/phpunit tests/
